//! End-to-end tests: every scenario runs the real binary against a real git,
//! inside a throwaway HOME (see `common::TestEnv`). The acceptance criteria
//! from the project brief are covered here.

mod common;

use std::fs;

use common::TestEnv;
use predicates::str::contains;

// ---------------------------------------------------------------------------
// init

#[test]
fn init_fresh_creates_everything() {
    let t = TestEnv::new();
    let out = t.ok(&["init"]);
    assert!(
        out.contains("Linked the routes file"),
        "unexpected output:\n{out}"
    );

    let routes = t.read(&t.routes_file());
    assert!(routes.contains("Generated by git-id"));

    let gitconfig = t.read(&t.gitconfig());
    assert!(gitconfig.contains("routes.gitconfig"));

    // Nothing existed before: no backup must be created.
    assert!(t.backups_of(&t.gitconfig()).is_empty());

    // Non-interactive: useConfigOnly is skipped with a notice.
    assert!(out.contains("Skipped user.useConfigOnly"));
}

#[test]
fn init_is_idempotent() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&["init"]);

    let includes = t.git_ok(
        &t.home,
        &["config", "--global", "--get-all", "include.path"],
    );
    assert_eq!(
        includes.lines().count(),
        1,
        "include.path must not be duplicated:\n{includes}"
    );
}

#[test]
fn init_preserves_existing_gitconfig_and_backs_it_up() {
    let t = TestEnv::new();
    let original = "# my precious config\n[alias]\n\tst = status\n";
    fs::write(t.gitconfig(), original).unwrap();

    t.ok(&["init"]);

    let after = t.read(&t.gitconfig());
    assert!(after.contains("# my precious config"));
    assert!(after.contains("st = status"));
    assert!(after.contains("routes.gitconfig"));

    let backups = t.backups_of(&t.gitconfig());
    assert_eq!(backups.len(), 1, "exactly one timestamped backup expected");
    assert_eq!(
        t.read(&backups[0]),
        original,
        "backup must be byte-identical"
    );

    // Re-running without changes must not create another backup.
    t.ok(&["init"]);
    assert_eq!(t.backups_of(&t.gitconfig()).len(), 1);
}

#[test]
fn init_use_config_only_flag() {
    let t = TestEnv::new();
    t.ok(&["init", "--use-config-only"]);
    let value = t.git_ok(
        &t.home,
        &["config", "--global", "--get", "user.useConfigOnly"],
    );
    assert_eq!(value, "true");
}

#[test]
fn init_writes_to_xdg_git_config_when_it_is_the_global_file() {
    let t = TestEnv::new();
    // git's rule: no ~/.gitconfig + existing $XDG_CONFIG_HOME/git/config
    // -> --global writes there.
    let xdg_git = t.mkdirs(".config/git").join("config");
    let original = "[init]\n\tdefaultBranch = main\n";
    fs::write(&xdg_git, original).unwrap();

    t.ok(&["init"]);

    assert!(!t.gitconfig().exists(), "~/.gitconfig must not be created");
    let after = t.read(&xdg_git);
    assert!(after.contains("defaultBranch"));
    assert!(after.contains("routes.gitconfig"));
    let backups = t.backups_of(&xdg_git);
    assert_eq!(backups.len(), 1);
    assert_eq!(t.read(&backups[0]), original);
}

#[test]
fn init_honors_git_config_global_override() {
    let t = TestEnv::new();
    // Point GIT_CONFIG_GLOBAL at a non-default file: `git config --global`
    // writes there, and git-id must back up and target that same file.
    let custom = t.home.join("custom-global.gitconfig");
    fs::write(&custom, "# preexisting global\n").unwrap();

    t.cmd()
        .env("GIT_CONFIG_GLOBAL", &custom)
        .args(["init", "--no-use-config-only"])
        .assert()
        .success();

    let after = t.read(&custom);
    assert!(after.contains("# preexisting global"), "content preserved");
    assert!(
        after.contains("routes.gitconfig"),
        "include added to the override"
    );
    assert_eq!(
        t.backups_of(&custom).len(),
        1,
        "the override file must be backed up"
    );
    assert!(
        !t.gitconfig().exists(),
        "~/.gitconfig must not be touched when GIT_CONFIG_GLOBAL is set"
    );
}

// ---------------------------------------------------------------------------
// create / show / edit / delete

#[test]
fn create_renders_exact_fragment() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane Doe",
        "--email",
        "jane@work.example",
        "--signing-key",
        "ABCDEF12",
        "--sign",
    ]);
    assert_eq!(
        t.read(&t.fragment("work")),
        "# git-id identity: work\n\
         [user]\n\
         \tname = Jane Doe\n\
         \temail = jane@work.example\n\
         \tsigningkey = ABCDEF12\n\
         [commit]\n\
         \tgpgsign = true\n"
    );

    let json: serde_json::Value = serde_json::from_str(&t.ok(&["show", "work", "--json"])).unwrap();
    assert_eq!(json["name"], "work");
    assert_eq!(json["user"]["name"], "Jane Doe");
    assert_eq!(json["user"]["email"], "jane@work.example");
    assert_eq!(json["user"]["signing_key"], "ABCDEF12");
    assert_eq!(json["user"]["sign"], true);
    assert_eq!(json["routes"], serde_json::json!([]));
}

#[test]
fn create_refuses_duplicates_unless_forced() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&["create", "x", "--name", "A", "--email", "a@b.co"]);
    t.cmd()
        .args(["create", "x", "--name", "B", "--email", "b@b.co"])
        .assert()
        .failure()
        .stderr(contains("already exists"));
    t.ok(&["create", "x", "--name", "B", "--email", "b@b.co", "--force"]);
    assert!(t.read(&t.fragment("x")).contains("b@b.co"));
}

#[test]
fn create_fails_fast_without_tty_instead_of_prompting() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.cmd()
        .args(["create", "work"])
        .assert()
        .failure()
        .stderr(contains("--name"));
    t.cmd()
        .args(["create", "work", "--name", "Jane Doe"])
        .assert()
        .failure()
        .stderr(contains("--email"));
}

#[test]
fn create_validates_slug_and_email() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    for bad_name in ["Work", "a b", "x.y", "café"] {
        t.cmd()
            .args(["create", bad_name, "--name", "A", "--email", "a@b.co"])
            .assert()
            .failure()
            .stderr(contains("slug"));
    }
    for bad_email in ["foo", "a@b", "a @b.co", "a@b@c.co"] {
        t.cmd()
            .args(["create", "ok-name", "--name", "A", "--email", bad_email])
            .assert()
            .failure()
            .stderr(contains("email"));
    }
}

#[test]
fn edit_with_flags_preserves_manual_keys() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane Doe",
        "--email",
        "jane@work.example",
    ]);

    // A key the user added by hand must survive `git-id edit`.
    let frag = t.fragment("work");
    t.git_ok(
        &t.home,
        &[
            "config",
            "--file",
            frag.to_str().unwrap(),
            "core.sshCommand",
            "ssh -i ~/.ssh/work",
        ],
    );

    t.ok(&["edit", "work", "--email", "new@work.example"]);

    let content = t.read(&frag);
    assert!(content.contains("new@work.example"));
    assert!(!content.contains("jane@work.example"));
    assert!(
        content.contains("sshCommand"),
        "manual key was lost:\n{content}"
    );
}

#[test]
fn edit_without_flags_and_without_editor_fails_clearly() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&["create", "x", "--name", "A", "--email", "a@b.co"]);
    t.cmd()
        .args(["edit", "x"])
        .assert()
        .failure()
        .stderr(contains("EDITOR"));
}

#[test]
fn delete_removes_identity_and_its_routes() {
    let t = TestEnv::new();
    t.setup_work();
    t.ok(&[
        "create",
        "personal",
        "--name",
        "Jane Doe",
        "--email",
        "jane@personal.example",
    ]);
    let personal_dir = t.mkdirs("dev/personal");
    t.ok(&["use", "personal", personal_dir.to_str().unwrap()]);

    // Refuses without confirmation when non-interactive.
    t.cmd()
        .args(["delete", "work"])
        .assert()
        .failure()
        .stderr(contains("--force"));

    t.ok(&["delete", "work", "--force"]);
    assert!(!t.fragment("work").exists());
    let routes = t.read(&t.routes_file());
    assert!(
        !routes.contains("work.gitconfig") && !routes.contains("dev/work"),
        "routes must be purged:\n{routes}"
    );
    assert!(
        routes.contains("personal.gitconfig"),
        "other identities must be untouched"
    );

    t.cmd()
        .args(["delete", "work", "--force"])
        .assert()
        .failure()
        .stderr(contains("does not exist"));
}

// ---------------------------------------------------------------------------
// use / unset / routes file

#[test]
fn use_writes_canonical_gitdir_with_trailing_slash() {
    let t = TestEnv::new();
    let dir = t.setup_work();

    let routes = t.read(&t.routes_file());
    let expected = format!("[includeIf \"gitdir:{}/\"]", t.git_path(&dir));
    assert!(
        routes.contains(&expected),
        "expected `{expected}` in:\n{routes}"
    );
    assert!(routes.contains("identities/work.gitconfig"));
}

#[test]
fn use_replaces_route_instead_of_duplicating() {
    let t = TestEnv::new();
    let dir = t.setup_work();
    t.ok(&[
        "create",
        "personal",
        "--name",
        "Jane Doe",
        "--email",
        "jane@personal.example",
    ]);
    let out = t.ok(&["use", "personal", dir.to_str().unwrap()]);
    assert!(out.contains("replaced"), "{out}");

    let routes = t.read(&t.routes_file());
    let gitdir_line = format!("[includeIf \"gitdir:{}/\"]", t.git_path(&dir));
    assert_eq!(
        routes.matches(&gitdir_line).count(),
        1,
        "exactly one block for the dir:\n{routes}"
    );
    assert!(routes.contains("personal.gitconfig"));
    assert!(!routes.contains("work.gitconfig"));

    // Routing to the same identity again is a friendly no-op.
    let out = t.ok(&["use", "personal", dir.to_str().unwrap()]);
    assert!(out.contains("already routed"), "{out}");
}

#[test]
fn use_accepts_tilde_paths_and_missing_dirs_with_warning() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&["create", "work", "--name", "J", "--email", "j@work.ai"]);

    let assert = t
        .cmd()
        .args(["use", "work", "~/future/dir"])
        .assert()
        .success()
        .stderr(contains("does not exist yet"));
    drop(assert);

    let routes = t.read(&t.routes_file());
    let expected = format!("[includeIf \"gitdir:{}/future/dir/\"]", t.git_path(&t.home));
    assert!(routes.contains(&expected), "{routes}");
}

#[test]
fn use_defaults_to_current_directory() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&["create", "work", "--name", "J", "--email", "j@work.ai"]);
    let dir = t.mkdirs("dev/work");
    t.cmd()
        .args(["use", "work"])
        .current_dir(&dir)
        .assert()
        .success();
    let routes = t.read(&t.routes_file());
    assert!(routes.contains(&format!("gitdir:{}/", t.git_path(&dir))));
}

#[test]
fn use_rejects_glob_paths_and_unknown_identities() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&["create", "work", "--name", "J", "--email", "j@work.ai"]);

    let weird = t.mkdirs("we[ird");
    t.cmd()
        .args(["use", "work", weird.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(contains("glob"));

    t.cmd()
        .args(["use", "nope", "/tmp"])
        .assert()
        .failure()
        .stderr(contains("does not exist"));
    // Routes must be untouched by failed attempts.
    let routes = t.read(&t.routes_file());
    assert!(!routes.contains("we[ird"));
    assert!(!routes.contains("nope"));
}

#[test]
fn unset_removes_route_and_is_idempotent() {
    let t = TestEnv::new();
    let dir = t.setup_work();

    let out = t.ok(&["unset", dir.to_str().unwrap()]);
    assert!(out.contains("Removed the route"), "{out}");
    assert!(!t.read(&t.routes_file()).contains("work"));

    let out = t.ok(&["unset", dir.to_str().unwrap()]);
    assert!(out.contains("nothing to do"), "{out}");
}

#[test]
fn unset_hints_about_covering_parent_route() {
    let t = TestEnv::new();
    let dir = t.setup_work();
    let child = t.mkdirs("dev/work/client");
    drop(dir);

    let out = t.ok(&["unset", child.to_str().unwrap()]);
    assert!(out.contains("nothing to do"), "{out}");
    assert!(out.contains("still covers"), "{out}");
}

#[test]
fn foreign_routes_content_survives_rewrites() {
    let t = TestEnv::new();
    let _ = t.setup_work();

    // Hand-added content in the routes file...
    let mut routes = t.read(&t.routes_file());
    routes.push_str(
        "\n[includeIf \"onbranch:main\"]\n\tpath = /tmp/foreign.inc\n[user]\n\tname = sneaky\n",
    );
    fs::write(t.routes_file(), routes).unwrap();

    // ...survives a full rewrite triggered by `use`.
    t.ok(&[
        "create",
        "personal",
        "--name",
        "Jane Doe",
        "--email",
        "jane@personal.example",
    ]);
    let dir = t.mkdirs("dev/personal");
    t.ok(&["use", "personal", dir.to_str().unwrap()]);

    let routes = t.read(&t.routes_file());
    assert!(routes.contains("onbranch:main"), "{routes}");
    assert!(routes.contains("sneaky"), "{routes}");
    assert!(routes.contains("personal.gitconfig"), "{routes}");

    // doctor reports it, as a warning (not an error).
    t.cmd()
        .arg("doctor")
        .assert()
        .success()
        .stdout(contains("not managed by git-id"));
}

// ---------------------------------------------------------------------------
// the acceptance scenario: clone -> commit with the right identity

#[test]
fn acceptance_repo_under_routed_dir_commits_with_identity() {
    let t = TestEnv::new();
    t.setup_work();
    let repo = t.init_repo("dev/work/some-repo");

    // Criterion 2: git resolves the routed identity with zero manual config.
    assert_eq!(
        t.git_ok(&repo, &["config", "--get", "user.email"]),
        "jane@work.example"
    );
    assert_eq!(
        t.git_ok(&repo, &["config", "--get", "user.name"]),
        "Jane Doe"
    );

    t.git_ok(&repo, &["commit", "--allow-empty", "-m", "first"]);
    assert_eq!(
        t.git_ok(&repo, &["log", "-1", "--format=%an <%ae>"]),
        "Jane Doe <jane@work.example>"
    );

    // Criterion 3: `which` answers correctly from a deep subdirectory.
    let deep = t.mkdirs("dev/work/some-repo/sub/deep");
    let out = t.ok(&["which", deep.to_str().unwrap()]);
    assert!(out.contains("work"), "{out}");
    assert!(out.contains("jane@work.example"), "{out}");
}

#[test]
fn acceptance_git_id_works_as_native_git_subcommand() {
    let t = TestEnv::new();
    t.setup_work();
    let repo = t.init_repo("dev/work/repo");

    // Put the freshly built binary on PATH and let *git* dispatch to it.
    // Build PATH with the platform separator so `git` finds `git-id`(.exe)
    // as the `id` subcommand on every OS.
    let bin = assert_cmd::cargo::cargo_bin("git-id");
    let mut search = vec![bin.parent().unwrap().to_path_buf()];
    search.extend(std::env::split_paths(
        &std::env::var_os("PATH").unwrap_or_default(),
    ));
    let path = std::env::join_paths(search).unwrap();

    let mut c = std::process::Command::new("git");
    c.env("HOME", &t.home)
        .env("XDG_CONFIG_HOME", t.home.join(".config"))
        .env("GIT_CONFIG_NOSYSTEM", "1")
        .env("LC_ALL", "C")
        .env("PATH", &path)
        .current_dir(&repo)
        .args(["id", "which"]);
    let out = c.output().unwrap();
    assert!(
        out.status.success(),
        "`git id which` failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("work"), "{stdout}");
}

#[test]
fn acceptance_use_config_only_blocks_unrouted_commits() {
    let t = TestEnv::new();
    t.ok(&["init", "--use-config-only"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane Doe",
        "--email",
        "jane@work.example",
    ]);
    let routed = t.mkdirs("dev/work");
    t.ok(&["use", "work", routed.to_str().unwrap()]);

    // Routed repo: commits fine.
    let good = t.init_repo("dev/work/repo");
    t.git_ok(&good, &["commit", "--allow-empty", "-m", "ok"]);

    // Unrouted repo: git must refuse to guess an identity.
    let stray = t.init_repo("elsewhere/stray");
    let out = t.git(&stray, &["commit", "--allow-empty", "-m", "nope"]);
    assert!(
        !out.status.success(),
        "commit must fail without an identity"
    );
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("useConfigOnly") || stderr.to_lowercase().contains("email"),
        "unexpected git error:\n{stderr}"
    );
}

#[test]
fn nested_routes_deepest_wins_in_git_and_in_which() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&[
        "create",
        "personal",
        "--name",
        "Jane Doe",
        "--email",
        "jane@personal.example",
    ]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane Doe",
        "--email",
        "jane@work.example",
    ]);
    let parent = t.mkdirs("dev");
    let child = t.mkdirs("dev/work");
    t.ok(&["use", "personal", parent.to_str().unwrap()]);
    t.ok(&["use", "work", child.to_str().unwrap()]);

    // The routes file must list the parent before the child (git: last wins).
    let routes = t.read(&t.routes_file());
    let parent_pos = routes.find("gitdir:").unwrap();
    let child_pos = routes.find("dev/work/").unwrap();
    assert!(parent_pos < child_pos, "{routes}");

    // Ground truth: a repo in the child dir gets the child identity...
    let repo = t.init_repo("dev/work/proj");
    assert_eq!(
        t.git_ok(&repo, &["config", "--get", "user.email"]),
        "jane@work.example"
    );
    // ...and a repo elsewhere under the parent gets the parent identity.
    let other = t.init_repo("dev/other");
    assert_eq!(
        t.git_ok(&other, &["config", "--get", "user.email"]),
        "jane@personal.example"
    );

    let out = t.ok(&["which", repo.to_str().unwrap()]);
    assert!(out.contains("work"), "{out}");
    let out = t.ok(&["which", other.to_str().unwrap()]);
    assert!(out.contains("personal"), "{out}");
}

// ---------------------------------------------------------------------------
// uninstall

#[test]
fn uninstall_removes_all_git_id_state() {
    let t = TestEnv::new();
    t.ok(&["init", "--use-config-only"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane Doe",
        "--email",
        "jane@work.example",
    ]);
    let dir = t.mkdirs("dev/work");
    t.ok(&["use", "work", dir.to_str().unwrap()]);
    assert!(t.config_dir().exists());

    let out = t.ok(&["uninstall", "--yes"]);

    assert!(!t.config_dir().exists(), "config dir must be removed");
    let includes = t.git(
        &t.home,
        &["config", "--global", "--get-all", "include.path"],
    );
    assert!(
        String::from_utf8_lossy(&includes.stdout).trim().is_empty(),
        "the include line must be removed"
    );
    let uco = t.git(
        &t.home,
        &["config", "--global", "--get", "user.useConfigOnly"],
    );
    assert!(!uco.status.success(), "user.useConfigOnly must be unset");
    assert!(
        out.contains("brew uninstall") && out.contains("cargo uninstall"),
        "should explain how to remove the binary:\n{out}"
    );
}

#[test]
fn uninstall_refuses_without_confirmation_when_noninteractive() {
    let t = TestEnv::new();
    t.setup_work();
    t.cmd()
        .arg("uninstall")
        .assert()
        .failure()
        .stderr(contains("--yes"));
    assert!(
        t.config_dir().exists(),
        "nothing should be removed without confirmation"
    );
}

// ---------------------------------------------------------------------------
// which / current

#[test]
fn which_json_shape_is_stable() {
    let t = TestEnv::new();
    t.setup_work();
    let repo = t.init_repo("dev/work/repo");

    let json: serde_json::Value =
        serde_json::from_str(&t.ok(&["which", repo.to_str().unwrap(), "--json"])).unwrap();
    assert_eq!(json["identity"], "work");
    assert_eq!(json["gitdir"], format!("{}/", t.git_path(&repo)));
    assert_eq!(json["route"], format!("{}/dev/work/", t.git_path(&t.home)));
    assert_eq!(json["name"], "Jane Doe");
    assert_eq!(json["email"], "jane@work.example");
    assert_eq!(json["in_repo"], true);
    assert_eq!(json["effective"]["email"], "jane@work.example");
    assert_eq!(json["mismatch"], false);
    let origin = json["effective"]["origin"].as_str().unwrap();
    assert!(origin.contains("work.gitconfig"), "{origin}");
}

#[test]
fn which_exits_nonzero_when_no_route_applies() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    let dir = t.mkdirs("unrouted");
    t.cmd()
        .args(["which", dir.to_str().unwrap()])
        .assert()
        .failure()
        .stdout(contains("No identity applies"));

    // Same through JSON: identity is null, exit code still 1.
    let assert = t
        .cmd()
        .args(["which", dir.to_str().unwrap(), "--json"])
        .assert()
        .failure();
    let json: serde_json::Value =
        serde_json::from_str(&String::from_utf8_lossy(&assert.get_output().stdout)).unwrap();
    assert_eq!(json["identity"], serde_json::Value::Null);
}

#[test]
fn which_detects_local_override_as_mismatch() {
    let t = TestEnv::new();
    t.setup_work();
    let repo = t.init_repo("dev/work/repo");
    t.git_ok(&repo, &["config", "user.email", "other@example.com"]);

    let assert = t
        .cmd()
        .args(["which", repo.to_str().unwrap(), "--json"])
        .assert()
        .success()
        .stderr(contains("overrides"));
    let json: serde_json::Value =
        serde_json::from_str(&String::from_utf8_lossy(&assert.get_output().stdout)).unwrap();
    assert_eq!(json["mismatch"], true);
    assert_eq!(json["effective"]["email"], "other@example.com");
    assert_eq!(json["email"], "jane@work.example");
}

#[test]
fn current_is_an_alias_for_which() {
    let t = TestEnv::new();
    let dir = t.setup_work();
    let out = t.ok(&["current", dir.to_str().unwrap()]);
    assert!(out.contains("work"), "{out}");
}

// ---------------------------------------------------------------------------
// list

#[test]
fn list_empty_is_friendly() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    let out = t.ok(&["list"]);
    assert!(out.contains("No identities yet"), "{out}");
}

#[test]
fn list_shows_identities_routes_and_json() {
    let t = TestEnv::new();
    let dir = t.setup_work();
    t.ok(&[
        "create",
        "personal",
        "--name",
        "Jane Doe",
        "--email",
        "jane@personal.example",
    ]);

    let out = t.ok(&["list"]);
    assert!(out.contains("work"), "{out}");
    assert!(out.contains("jane@work.example"), "{out}");
    assert!(out.contains("personal"), "{out}");
    assert!(out.contains("(no routes)"), "{out}");

    let out = t.ok(&["list", "--paths"]);
    assert!(out.contains("->  work"), "{out}");

    let json: serde_json::Value = serde_json::from_str(&t.ok(&["list", "--json"])).unwrap();
    let arr = json.as_array().unwrap();
    assert_eq!(arr.len(), 2);
    // Identities are listed sorted by name: `personal` before `work`.
    assert_eq!(arr[0]["name"], "personal");
    assert_eq!(arr[0]["routes"], serde_json::json!([]));
    assert_eq!(arr[1]["name"], "work");
    assert_eq!(arr[1]["user"]["email"], "jane@work.example");
    assert_eq!(
        arr[1]["routes"],
        serde_json::json!([format!("{}/", t.git_path(&dir))])
    );
}

// ---------------------------------------------------------------------------
// doctor / completions

#[test]
fn doctor_healthy_setup_passes() {
    let t = TestEnv::new();
    t.setup_work();
    t.cmd().arg("doctor").assert().success();
}

#[test]
fn doctor_flags_missing_fragment_and_missing_include() {
    let t = TestEnv::new();
    t.setup_work();

    fs::remove_file(t.fragment("work")).unwrap();
    t.cmd()
        .arg("doctor")
        .assert()
        .failure()
        .stdout(contains("work"));

    t.git_ok(
        &t.home,
        &["config", "--global", "--unset-all", "include.path"],
    );
    t.cmd()
        .arg("doctor")
        .assert()
        .failure()
        .stdout(contains("git-id init"));
}

#[test]
fn doctor_flags_invalid_gpg_format() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane Doe",
        "--email",
        "jane@work.example",
    ]);
    // A hand-edited fragment can hold a bogus gpg.format value (git only fails
    // at signing time); doctor flags it as a warning, not a hard error.
    t.git_ok(
        &t.home,
        &[
            "config",
            "--file",
            t.fragment("work").to_str().unwrap(),
            "gpg.format",
            "pgp",
        ],
    );
    t.cmd()
        .arg("doctor")
        .assert()
        .success()
        .stdout(contains("openpgp, ssh or x509"));
}

#[test]
fn completions_generate_for_bash_and_zsh() {
    let t = TestEnv::new();
    for shell in ["bash", "zsh", "fish", "nushell"] {
        let out = t.ok(&["completions", shell]);
        assert!(out.contains("git-id"), "empty {shell} completions");
    }
}

#[test]
fn completions_install_writes_autoloaded_file() {
    let t = TestEnv::new();
    let out = t.ok(&["completions", "install", "fish"]);
    let f = t.home.join(".config/fish/completions/git-id.fish");
    assert!(f.exists(), "fish completion file was not written");
    assert!(t.read(&f).contains("git-id"));
    assert!(out.contains("fish completions"), "{out}");
}

#[test]
fn completions_install_reports_manual_step_for_nushell() {
    // With no autoloading nushell reachable (the fake one fails the autoload-dir
    // probe), install falls back to the config.nu location and prints the hint.
    let t = TestEnv::new();
    let bin = t.fake_bin(&["nu"]);
    let assert = t
        .cmd()
        .env("PATH", &bin)
        .args(["completions", "install", "nushell"])
        .assert()
        .success();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).into_owned();
    let f = t.home.join(".config/nushell/completions/git-id.nu");
    assert!(f.exists(), "nushell completion file was not written");
    assert!(out.contains("config.nu"), "missing activation hint:\n{out}");
}

#[test]
fn completions_print_detects_shell_from_env() {
    // The print-to-stdout path still resolves a single shell; with no
    // version vars in the env it falls back to $SHELL.
    let t = TestEnv::new();
    let assert = t
        .cmd()
        .env("SHELL", "/bin/bash")
        .env_remove("NU_VERSION")
        .env_remove("FISH_VERSION")
        .args(["completions"])
        .assert()
        .success();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).into_owned();
    assert!(
        out.contains("git-id"),
        "expected a completion script:\n{out}"
    );
    // A bash script, not zsh — confirms $SHELL drove detection here.
    assert!(!out.contains("#compdef"), "should be bash, not zsh:\n{out}");
}

#[test]
fn completions_install_targets_all_detected_shells() {
    // No shell argument: install for every shell on PATH. An isolated fake PATH
    // keeps it hermetic (install never shells out, so PATH can be replaced).
    let t = TestEnv::new();
    let bin = t.fake_bin(&["zsh", "nu"]);
    let assert = t
        .cmd()
        .env("PATH", &bin)
        .args(["completions", "install"])
        .assert()
        .success();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).into_owned();
    assert!(
        t.home.join(".zfunc/_git-id").exists(),
        "zsh completion missing:\n{out}"
    );
    assert!(
        t.home
            .join(".config/nushell/completions/git-id.nu")
            .exists(),
        "nushell completion missing:\n{out}"
    );
    assert!(out.contains("zsh completions"), "{out}");
    assert!(out.contains("nushell completions"), "{out}");
}

#[test]
fn completions_install_single_shell_targets_only_it() {
    // An explicit shell installs just that one, ignoring what is on PATH. The
    // fake (failing) zsh makes target resolution fall back to ~/.zfunc, keeping
    // the test off the real filesystem.
    let t = TestEnv::new();
    let bin = t.fake_bin(&["zsh", "nu"]);
    t.cmd()
        .env("PATH", &bin)
        .args(["completions", "install", "zsh"])
        .assert()
        .success();
    assert!(t.home.join(".zfunc/_git-id").exists());
    assert!(
        !t.home
            .join(".config/nushell/completions/git-id.nu")
            .exists(),
        "should not have installed nushell"
    );
}

#[test]
fn completions_install_current_targets_only_the_running_shell() {
    // --current installs just the detected shell. NU_VERSION makes detection
    // deterministic (nushell) regardless of host or $SHELL.
    let t = TestEnv::new();
    let bin = t.fake_bin(&["zsh", "nu"]);
    t.cmd()
        .env("PATH", &bin)
        .env("NU_VERSION", "0.99.0")
        .args(["completions", "install", "--current"])
        .assert()
        .success();
    assert!(
        t.home
            .join(".config/nushell/completions/git-id.nu")
            .exists(),
        "nushell (current) completion should be installed"
    );
    assert!(
        !t.home.join(".zfunc/_git-id").exists(),
        "--current should not install other detected shells"
    );
}

#[test]
fn completions_install_is_idempotent() {
    let t = TestEnv::new();
    let bin = t.fake_bin(&["zsh"]);
    t.cmd()
        .env("PATH", &bin)
        .args(["completions", "install"])
        .assert()
        .success();
    let assert = t
        .cmd()
        .env("PATH", &bin)
        .args(["completions", "install"])
        .assert()
        .success();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).into_owned();
    assert!(
        out.contains("already up to date"),
        "a second install should be a no-op:\n{out}"
    );
}

#[test]
fn completions_install_activate_edits_zshrc_idempotently() {
    // zsh resolves to the ~/.zfunc fallback (fake zsh fails the $fpath probe),
    // so --activate writes the fpath+compinit block into ~/.zshrc.
    let t = TestEnv::new();
    let bin = t.fake_bin(&["zsh"]);
    t.cmd()
        .env("PATH", &bin)
        .args(["completions", "install", "zsh", "--activate"])
        .assert()
        .success();
    let zshrc = t.home.join(".zshrc");
    let body = t.read(&zshrc);
    assert!(
        body.contains("git-id completions"),
        "marker missing:\n{body}"
    );
    assert!(body.contains("compinit"), "compinit missing:\n{body}");

    // A second --activate must not duplicate the block.
    t.cmd()
        .env("PATH", &bin)
        .args(["completions", "install", "zsh", "--activate"])
        .assert()
        .success();
    assert_eq!(
        t.read(&zshrc),
        body,
        "second --activate duplicated the block"
    );
}

#[test]
fn uninstall_removes_completion_files_and_activation() {
    let t = TestEnv::new();
    let path = t.path_with_fake_bin(&["zsh"]);
    t.cmd().env("PATH", &path).args(["init"]).assert().success();
    t.cmd()
        .env("PATH", &path)
        .args(["completions", "install", "zsh", "--activate"])
        .assert()
        .success();
    let zshrc = t.home.join(".zshrc");
    assert!(t.read(&zshrc).contains("git-id completions"));
    assert!(t.home.join(".zfunc/_git-id").exists());

    t.cmd()
        .env("PATH", &path)
        .args(["uninstall", "--yes"])
        .assert()
        .success();
    assert!(
        !t.read(&zshrc).contains("git-id completions"),
        "uninstall should remove the rc activation block"
    );
    assert!(
        !t.home.join(".zfunc/_git-id").exists(),
        "uninstall should remove the completion file"
    );
}

#[test]
fn init_installs_completions_for_detected_shells() {
    // init must keep git reachable, so prepend the fake shells to the real PATH.
    let t = TestEnv::new();
    let path = t.path_with_fake_bin(&["zsh", "nu"]);
    t.cmd().env("PATH", path).args(["init"]).assert().success();
    assert!(
        t.home.join(".zfunc/_git-id").exists(),
        "init did not install zsh completion"
    );
    assert!(
        t.home
            .join(".config/nushell/completions/git-id.nu")
            .exists(),
        "init did not install nushell completion"
    );
}

#[test]
fn doctor_reports_completion_status_per_shell() {
    let t = TestEnv::new();
    let path = t.path_with_fake_bin(&["zsh", "nu"]);
    // Install only zsh; nushell is detected but its file is absent. Both steps
    // use the same fake (failing) shells so target resolution falls back to the
    // sandbox consistently (zsh -> ~/.zfunc), instead of the host's real shells.
    t.cmd()
        .env("PATH", &path)
        .args(["completions", "install", "zsh"])
        .assert()
        .success();
    let assert = t.cmd().env("PATH", &path).args(["doctor"]).assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).into_owned();
    assert!(
        out.contains("zsh completion installed"),
        "doctor should report zsh installed:\n{out}"
    );
    assert!(
        out.contains("nushell completion not installed"),
        "doctor should report nushell missing:\n{out}"
    );
}

#[test]
fn man_prints_a_roff_page() {
    let t = TestEnv::new();
    let out = t.ok(&["man"]);
    assert!(
        out.contains(".TH git-id"),
        "`man` should print roff:\n{out}"
    );
    assert!(out.contains("create"), "should list subcommands");
}

#[test]
#[cfg(unix)]
fn init_installs_the_man_page_and_uninstall_removes_it() {
    let t = TestEnv::new();
    // The test binary lives at `target/debug/git-id` (parent not `bin`), so the
    // page lands in the XDG data dir the sandbox controls.
    let page = t.home.join(".local/share/man/man1/git-id.1");

    let out = t.ok(&["init"]);
    assert!(
        page.exists(),
        "init should install the man page at {}",
        page.display()
    );
    assert!(
        out.contains("man page"),
        "init should report installing it:\n{out}"
    );
    assert!(t.read(&page).contains(".TH git-id"));

    t.ok(&["uninstall", "--yes"]);
    assert!(!page.exists(), "uninstall should remove the man page");
}

// ---------------------------------------------------------------------------
// input validation / injection

#[test]
fn create_rejects_control_chars_in_signing_key() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    // A newline in the signing key would otherwise inject a gitconfig section
    // (e.g. core.sshCommand) into the fragment git includes for routed repos.
    t.cmd()
        .args([
            "create",
            "work",
            "--name",
            "Jane",
            "--email",
            "jane@work.example",
            "--signing-key",
            "KEY\n[core]\n\tsshCommand = touch PWNED",
        ])
        .assert()
        .failure()
        .stderr(contains("control characters"));
    assert!(
        !t.fragment("work").exists(),
        "no fragment must be written when validation fails"
    );
}

// ---------------------------------------------------------------------------
// edit: signing-key removal, sign toggles, and atomic validation

#[test]
fn edit_removes_signing_key_and_toggles_sign_preserving_manual_keys() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane Doe",
        "--email",
        "jane@work.example",
        "--signing-key",
        "ABCDEF12",
        "--sign",
    ]);
    // A hand-added key must survive edits.
    let frag = t.fragment("work");
    t.git_ok(
        &t.home,
        &[
            "config",
            "--file",
            frag.to_str().unwrap(),
            "core.sshCommand",
            "ssh -i ~/.ssh/work",
        ],
    );

    t.ok(&["edit", "work", "--signing-key", ""]); // remove the key
    t.ok(&["edit", "work", "--no-sign"]); // turn signing off

    let json: serde_json::Value = serde_json::from_str(&t.ok(&["show", "work", "--json"])).unwrap();
    assert_eq!(json["user"]["signing_key"], serde_json::Value::Null);
    assert_eq!(json["user"]["sign"], false);

    let content = t.read(&frag);
    assert!(
        !content.contains("signingkey"),
        "signing key not removed:\n{content}"
    );
    assert!(
        content.contains("sshCommand"),
        "manual key lost:\n{content}"
    );
}

// ---------------------------------------------------------------------------
// gpg.format and per-identity SSH key (core.sshCommand)

#[test]
fn create_sets_gpg_format_and_ssh_key() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane Doe",
        "--email",
        "jane@work.example",
        "--format",
        "ssh",
        "--ssh-key",
        "/home/jane/.ssh/id_work",
    ]);

    // `--ssh-key` is sugar for a deterministic, agent-proof command.
    assert_eq!(
        t.read(&t.fragment("work")),
        "# git-id identity: work\n\
         [user]\n\
         \tname = Jane Doe\n\
         \temail = jane@work.example\n\
         [gpg]\n\
         \tformat = ssh\n\
         [core]\n\
         \tsshCommand = ssh -i '/home/jane/.ssh/id_work' -o IdentitiesOnly=yes\n"
    );

    let json: serde_json::Value = serde_json::from_str(&t.ok(&["show", "work", "--json"])).unwrap();
    assert_eq!(json["user"]["format"], "ssh");
    assert_eq!(
        json["user"]["ssh_command"],
        "ssh -i '/home/jane/.ssh/id_work' -o IdentitiesOnly=yes"
    );
}

#[test]
fn create_stores_raw_ssh_command_verbatim() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane Doe",
        "--email",
        "jane@work.example",
        "--ssh-command",
        "ssh -i ~/.ssh/id_work -p 2222",
    ]);

    let json: serde_json::Value = serde_json::from_str(&t.ok(&["show", "work", "--json"])).unwrap();
    assert_eq!(json["user"]["ssh_command"], "ssh -i ~/.ssh/id_work -p 2222");
    assert_eq!(json["user"]["format"], serde_json::Value::Null);
}

#[test]
fn ssh_key_and_ssh_command_are_mutually_exclusive() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.cmd()
        .args([
            "create",
            "work",
            "--name",
            "Jane",
            "--email",
            "jane@work.example",
            "--ssh-key",
            "/k",
            "--ssh-command",
            "ssh -i /k",
        ])
        .assert()
        .failure();
    assert!(!t.fragment("work").exists());
}

#[test]
fn create_rejects_control_chars_in_ssh_command() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    // A newline would otherwise inject a gitconfig section into the fragment.
    t.cmd()
        .args([
            "create",
            "work",
            "--name",
            "Jane",
            "--email",
            "jane@work.example",
            "--ssh-command",
            "ssh\n[user]\n\temail = evil@x.co",
        ])
        .assert()
        .failure()
        .stderr(contains("control characters"));
    assert!(!t.fragment("work").exists());
}

#[test]
fn edit_sets_and_removes_format_and_ssh() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane Doe",
        "--email",
        "jane@work.example",
    ]);

    t.ok(&[
        "edit",
        "work",
        "--format",
        "ssh",
        "--ssh-key",
        "/home/jane/.ssh/id_work",
    ]);
    let json: serde_json::Value = serde_json::from_str(&t.ok(&["show", "work", "--json"])).unwrap();
    assert_eq!(json["user"]["format"], "ssh");
    assert_eq!(
        json["user"]["ssh_command"],
        "ssh -i '/home/jane/.ssh/id_work' -o IdentitiesOnly=yes"
    );

    t.ok(&["edit", "work", "--no-format", "--no-ssh"]);
    let json: serde_json::Value = serde_json::from_str(&t.ok(&["show", "work", "--json"])).unwrap();
    assert_eq!(json["user"]["format"], serde_json::Value::Null);
    assert_eq!(json["user"]["ssh_command"], serde_json::Value::Null);

    let content = t.read(&t.fragment("work"));
    assert!(
        !content.contains("format") && !content.contains("sshCommand"),
        "format/ssh not removed:\n{content}"
    );
}

#[test]
fn edit_rejects_invalid_field_without_partial_write() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Old Name",
        "--email",
        "old@work.example",
    ]);

    // Valid name + invalid email: the whole patch must be rejected as a no-op,
    // not leave the name already written.
    t.cmd()
        .args([
            "edit",
            "work",
            "--name",
            "New Name",
            "--email",
            "not-an-email",
        ])
        .assert()
        .failure()
        .stderr(contains("email"));

    let content = t.read(&t.fragment("work"));
    assert!(
        content.contains("Old Name") && !content.contains("New Name"),
        "partial write occurred:\n{content}"
    );
    assert!(content.contains("old@work.example"));
}

// ---------------------------------------------------------------------------
// include detection across global config files (XDG vs ~/.gitconfig)

#[test]
fn include_in_xdg_is_found_and_removed_after_home_gitconfig_appears() {
    let t = TestEnv::new();
    // Force the include into the XDG git config: no ~/.gitconfig, but an
    // existing $XDG_CONFIG_HOME/git/config makes that the --global write target.
    let xdg_git = t.mkdirs(".config/git").join("config");
    fs::write(&xdg_git, "[init]\n\tdefaultBranch = main\n").unwrap();
    t.ok(&["init", "--no-use-config-only"]);
    assert!(!t.gitconfig().exists());
    assert!(t.read(&xdg_git).contains("routes.gitconfig"));

    // A ~/.gitconfig appears later (e.g. another tool). `git config --global`
    // would now go blind to the XDG include; git-id scans the files directly.
    fs::write(t.gitconfig(), "[user]\n\tname = Someone\n").unwrap();

    t.cmd()
        .arg("doctor")
        .assert()
        .success()
        .stdout(contains("includes the routes file"));

    t.ok(&["uninstall", "--yes"]);
    let after = t.read(&xdg_git);
    assert!(
        !after.contains("routes.gitconfig"),
        "the XDG include must be removed:\n{after}"
    );
    assert!(
        after.contains("defaultBranch"),
        "unrelated XDG content must be preserved:\n{after}"
    );
}

// ---------------------------------------------------------------------------
// init edge cases

#[test]
fn init_useconfigonly_already_enabled_is_idempotent() {
    let t = TestEnv::new();
    t.ok(&["init", "--use-config-only"]);
    assert!(t.backups_of(&t.gitconfig()).is_empty());

    let out = t.ok(&["init"]);
    assert!(out.contains("already enabled"), "{out}");
    assert!(
        t.backups_of(&t.gitconfig()).is_empty(),
        "a no-op re-run must not take a backup"
    );
}

#[test]
fn init_with_nonexistent_git_config_global_creates_it_without_backup() {
    let t = TestEnv::new();
    let custom = t.home.join("fresh-global.gitconfig");
    t.cmd()
        .env("GIT_CONFIG_GLOBAL", &custom)
        .args(["init", "--no-use-config-only"])
        .assert()
        .success();
    assert!(custom.exists(), "the override file should be created");
    assert!(t.read(&custom).contains("routes.gitconfig"));
    assert!(
        t.backups_of(&custom).is_empty(),
        "a fresh (nonexistent) target must not be backed up"
    );
    assert!(!t.gitconfig().exists(), "~/.gitconfig must not be created");
}

// ---------------------------------------------------------------------------
// doctor: path-form and duplicate diagnostics

#[test]
fn doctor_flags_noncanonical_route() {
    let t = TestEnv::new();
    t.setup_work();
    // Hand-write a route whose gitdir is non-canonical (contains `..`) but still
    // resolves to an existing directory: doctor must flag it via the canonical
    // comparison (which now runs in git-path form).
    let home = t.git_path(&t.home);
    let frag = t.git_path(&t.fragment("work"));
    let routes =
        format!("# header\n[includeIf \"gitdir:{home}/dev/work/../work/\"]\n\tpath = \"{frag}\"\n");
    fs::write(t.routes_file(), routes).unwrap();

    t.cmd()
        .arg("doctor")
        .assert()
        .stdout(contains("differs from the directory's canonical path"));
}

#[test]
fn doctor_flags_duplicate_gitdir_across_preserved_and_managed() {
    let t = TestEnv::new();
    let dir = t.setup_work();
    let gitdir = format!("{}/", t.git_path(&dir));
    let frag = t.git_path(&t.fragment("work"));
    // Append a hand-edited includeIf for the SAME gitdir with an extra key, so
    // it is bucketed as `preserved`, not a managed entry. git applies both.
    let mut routes = t.read(&t.routes_file());
    routes.push_str(&format!(
        "\n[includeIf \"gitdir:{gitdir}\"]\n\tpath = \"{frag}\"\n\tsshCommand = ssh -i x\n"
    ));
    fs::write(t.routes_file(), routes).unwrap();

    t.cmd()
        .arg("doctor")
        .assert()
        .failure()
        .stdout(contains("routes exist for"));
}

// ---------------------------------------------------------------------------
// use: linked worktree

#[test]
fn use_warns_when_routing_a_linked_worktree() {
    let t = TestEnv::new();
    t.ok(&["init"]);
    t.ok(&[
        "create",
        "work",
        "--name",
        "Jane",
        "--email",
        "jane@work.example",
    ]);

    let main = t.init_repo("dev/main");
    // dev/main is not routed, so give the setup commit an explicit identity:
    // CI runners (unlike a dev macOS box) have no auto-guessable git ident.
    t.git_ok(
        &main,
        &[
            "-c",
            "user.name=Test",
            "-c",
            "user.email=test@example.com",
            "commit",
            "--allow-empty",
            "-m",
            "init",
        ],
    );
    let wt = t.home.join("dev/wt");
    t.git_ok(&main, &["worktree", "add", wt.to_str().unwrap()]);

    // git matches routes against the main repo, so a route on the worktree's own
    // path would never apply — `use` must say so instead of silently succeeding.
    t.cmd()
        .args(["use", "work", wt.to_str().unwrap()])
        .assert()
        .success()
        .stderr(contains("linked worktree"));
}
