//! The routing file `routes.gitconfig`, fully owned and regenerated by
//! git-id.
//!
//! Entries are rendered sorted by gitdir. With trailing slashes, an ancestor
//! directory is a strict string prefix of its descendants, so the sort
//! guarantees parent-before-child order — and since git gives precedence to
//! the *last* value found, the deepest (most specific) route always wins.
//!
//! Anything in the file that is not a plain `[includeIf "gitdir:..."]` block
//! with only `path = ...` keys (e.g. hand-added `onbranch:` includes) is kept
//! verbatim in a `preserved` bucket and re-emitted on every save; `doctor`
//! flags it.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::env::Env;
use crate::paths;
use crate::store;

const HEADER: &str = "# Generated by git-id — do not edit by hand; your changes may be overwritten.\n\
                      # Inspect routes with `git-id list --paths`; change them with `git-id use` / `git-id unset`.\n";

#[derive(Debug, Clone, PartialEq)]
pub struct RouteEntry {
    /// Absolute directory with trailing slash, as stored in the
    /// `gitdir:` pattern.
    pub gitdir: String,
    /// The included file (an identity fragment when managed).
    pub target: PathBuf,
    /// Whether `target` is one of our identity fragments.
    pub managed: bool,
}

impl RouteEntry {
    /// Identity name for managed entries (`.../identities/<name>.gitconfig`).
    pub fn identity(&self) -> Option<&str> {
        if !self.managed {
            return None;
        }
        self.target.file_stem()?.to_str()
    }
}

#[derive(Debug, Default, PartialEq)]
pub struct Routes {
    /// Foreign blocks kept verbatim (each one a multi-line chunk).
    pub preserved: Vec<String>,
    pub entries: Vec<RouteEntry>,
}

impl Routes {
    /// Add or replace the route for `gitdir` (no duplicates, ever).
    pub fn set_route(&mut self, gitdir: &str, target: PathBuf, env: &Env) {
        self.entries.retain(|e| e.gitdir != gitdir);
        let managed = is_managed(&target, env);
        self.entries.push(RouteEntry {
            gitdir: gitdir.to_string(),
            target,
            managed,
        });
    }

    /// Remove the route for exactly `gitdir`; returns whether one existed.
    pub fn remove_gitdir(&mut self, gitdir: &str) -> bool {
        let before = self.entries.len();
        self.entries.retain(|e| e.gitdir != gitdir);
        self.entries.len() != before
    }

    /// Remove every route pointing at identity `name`; returns their gitdirs.
    pub fn remove_identity(&mut self, name: &str) -> Vec<String> {
        let (removed, kept): (Vec<_>, Vec<_>) = std::mem::take(&mut self.entries)
            .into_iter()
            .partition(|e| e.identity() == Some(name));
        self.entries = kept;
        removed.into_iter().map(|e| e.gitdir).collect()
    }

    /// Gitdirs routed to identity `name`, sorted.
    pub fn gitdirs_for_identity(&self, name: &str) -> Vec<&str> {
        let mut dirs: Vec<&str> = self
            .entries
            .iter()
            .filter(|e| e.identity() == Some(name))
            .map(|e| e.gitdir.as_str())
            .collect();
        dirs.sort_unstable();
        dirs
    }

    /// The most specific route covering `query` (an absolute dir with
    /// trailing slash). Mirrors git's behavior: all matching includes apply,
    /// the last one in sorted order — the longest prefix — wins.
    pub fn longest_match(&self, query: &str) -> Option<&RouteEntry> {
        self.entries
            .iter()
            .filter(|e| query.starts_with(&e.gitdir))
            .max_by_key(|e| e.gitdir.len())
    }
}

fn is_managed(target: &Path, env: &Env) -> bool {
    target.starts_with(&env.identities_dir)
        && target.extension().and_then(|e| e.to_str()) == Some(store::FRAGMENT_EXT)
}

pub fn load(env: &Env) -> Result<Routes> {
    match std::fs::read_to_string(&env.routes_file) {
        Ok(text) => Ok(parse(&text, env)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Routes::default()),
        Err(e) => Err(e).with_context(|| format!("cannot read {}", env.routes_file.display())),
    }
}

pub fn save(env: &Env, routes: &Routes) -> Result<()> {
    store::atomic_write(&env.routes_file, &render(routes))
}

pub fn render(routes: &Routes) -> String {
    let mut out = String::from(HEADER);
    for block in &routes.preserved {
        out.push('\n');
        out.push_str(block.trim_end_matches('\n'));
        out.push('\n');
    }
    let mut entries: Vec<&RouteEntry> = routes.entries.iter().collect();
    entries.sort_by(|a, b| a.gitdir.cmp(&b.gitdir));
    for entry in entries {
        let target = entry
            .target
            .to_str()
            .expect("targets originate from UTF-8 validated paths");
        // Write the include target in git-path form too, so the file Git reads
        // uses forward slashes on Windows (and is unchanged on Unix).
        let target = paths::to_git_path(target);
        out.push('\n');
        out.push_str(&format!(
            "[includeIf \"gitdir:{}\"]\n\tpath = {}\n",
            escape_subsection(&entry.gitdir),
            quote_value(&target),
        ));
    }
    out
}

/// Parse the routing file. The format is the one we own; blocks we do not
/// fully understand are preserved verbatim rather than dropped.
pub fn parse(text: &str, env: &Env) -> Routes {
    struct Block<'t> {
        header: Option<&'t str>,
        lines: Vec<&'t str>,
    }
    let mut blocks = vec![Block {
        header: None,
        lines: Vec::new(),
    }];
    for line in text.lines() {
        if line.trim_start().starts_with('[') {
            blocks.push(Block {
                header: Some(line),
                lines: Vec::new(),
            });
        } else {
            blocks.last_mut().expect("never empty").lines.push(line);
        }
    }

    let mut routes = Routes::default();
    for block in blocks {
        let Some(header) = block.header else {
            // Preamble: comments and blanks belong to our generated header
            // and are regenerated; naked keys (invalid gitconfig) are kept.
            let substantive: Vec<&str> = block
                .lines
                .iter()
                .copied()
                .filter(|l| is_substantive(l))
                .collect();
            if !substantive.is_empty() {
                routes.preserved.push(substantive.join("\n"));
            }
            continue;
        };

        let gitdir = parse_gitdir_header(header);
        let mut paths = Vec::new();
        let mut understood = gitdir.is_some();
        if understood {
            for line in block.lines.iter().copied().filter(|l| is_substantive(l)) {
                match parse_path_line(line) {
                    Some(value) => paths.push(value),
                    None => {
                        understood = false;
                        break;
                    }
                }
            }
        }

        if understood && !paths.is_empty() {
            let gitdir = gitdir.expect("checked above");
            for value in paths {
                let target = paths::expand_tilde(&value, &env.home);
                let managed = is_managed(&target, env);
                routes.entries.push(RouteEntry {
                    gitdir: gitdir.clone(),
                    target,
                    managed,
                });
            }
        } else {
            // Foreign or partially understood block: keep it verbatim.
            let mut raw = header.to_string();
            for line in &block.lines {
                raw.push('\n');
                raw.push_str(line);
            }
            routes.preserved.push(raw.trim_end().to_string());
        }
    }
    routes
}

fn is_substantive(line: &str) -> bool {
    let t = line.trim();
    !t.is_empty() && !t.starts_with('#') && !t.starts_with(';')
}

/// `[includeIf "gitdir:<pattern>"]` -> `<pattern>` (with subsection
/// unescaping). Conditions other than plain case-sensitive `gitdir:` —
/// e.g. `gitdir/i:`, `onbranch:`, `hasconfig:` — are treated as foreign.
fn parse_gitdir_header(line: &str) -> Option<String> {
    let t = line.trim();
    let inner = t.strip_prefix('[')?.strip_suffix(']')?.trim();
    let (section, rest) = inner.split_once('"')?;
    if !section.trim().eq_ignore_ascii_case("includeif") {
        return None;
    }
    let subsection_raw = rest.strip_suffix('"')?;
    let subsection = unescape_subsection(subsection_raw);
    subsection.strip_prefix("gitdir:").map(str::to_string)
}

/// `path = <value>` -> unquoted `<value>`.
fn parse_path_line(line: &str) -> Option<String> {
    let (key, value) = line.split_once('=')?;
    if !key.trim().eq_ignore_ascii_case("path") {
        return None;
    }
    Some(unquote_value(value.trim()))
}

fn escape_subsection(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '\\' => vec!['\\', '\\'],
            '"' => vec!['\\', '"'],
            c => vec![c],
        })
        .collect()
}

fn unescape_subsection(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c == '\\' {
            if let Some(next) = chars.next() {
                out.push(next);
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Render a gitconfig value, always quoted (deterministic, and safe for
/// paths containing spaces, `#` or `;`).
fn quote_value(s: &str) -> String {
    let escaped: String = s
        .chars()
        .flat_map(|c| match c {
            '\\' => vec!['\\', '\\'],
            '"' => vec!['\\', '"'],
            c => vec![c],
        })
        .collect();
    format!("\"{escaped}\"")
}

fn unquote_value(s: &str) -> String {
    if let Some(rest) = s.strip_prefix('"') {
        let mut out = String::with_capacity(rest.len());
        let mut chars = rest.chars();
        while let Some(c) = chars.next() {
            match c {
                '"' => break,
                '\\' => {
                    if let Some(next) = chars.next() {
                        out.push(next);
                    }
                }
                c => out.push(c),
            }
        }
        out
    } else {
        // Unquoted: a `#` or `;` starts a comment.
        let end = s.find(['#', ';']).unwrap_or(s.len());
        s[..end].trim_end().to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsString;

    fn test_env() -> Env {
        Env::new(
            PathBuf::from("/home/test"),
            PathBuf::from("/home/test"),
            None::<OsString>,
        )
    }

    fn entry(env: &Env, gitdir: &str, name: &str) -> RouteEntry {
        RouteEntry {
            gitdir: gitdir.to_string(),
            target: store::fragment_path(env, name),
            managed: true,
        }
    }

    #[test]
    fn render_is_sorted_parent_before_child() {
        let env = test_env();
        let routes = Routes {
            preserved: Vec::new(),
            entries: vec![
                entry(&env, "/home/test/dev/work/", "work"),
                entry(&env, "/home/test/dev/", "personal"),
            ],
        };
        let text = render(&routes);
        let parent = text.find("gitdir:/home/test/dev/\"").unwrap();
        let child = text.find("gitdir:/home/test/dev/work/\"").unwrap();
        assert!(
            parent < child,
            "parent must come first so the deeper route wins:\n{text}"
        );
    }

    #[test]
    fn parse_render_roundtrip() {
        let env = test_env();
        let mut routes = Routes::default();
        routes.set_route(
            "/home/test/dev/work/",
            store::fragment_path(&env, "work"),
            &env,
        );
        routes.set_route(
            "/home/test/dev/",
            store::fragment_path(&env, "personal"),
            &env,
        );
        let text = render(&routes);
        let reparsed = parse(&text, &env);
        assert_eq!(reparsed.preserved, Vec::<String>::new());
        let mut original = routes.entries.clone();
        original.sort_by(|a, b| a.gitdir.cmp(&b.gitdir));
        assert_eq!(reparsed.entries, original);
    }

    #[test]
    fn set_route_replaces_existing() {
        let env = test_env();
        let mut routes = Routes::default();
        routes.set_route("/d/", store::fragment_path(&env, "one"), &env);
        routes.set_route("/d/", store::fragment_path(&env, "two"), &env);
        assert_eq!(routes.entries.len(), 1);
        assert_eq!(routes.entries[0].identity(), Some("two"));
    }

    #[test]
    fn remove_identity_returns_gitdirs() {
        let env = test_env();
        let mut routes = Routes::default();
        routes.set_route("/a/", store::fragment_path(&env, "x"), &env);
        routes.set_route("/b/", store::fragment_path(&env, "x"), &env);
        routes.set_route("/c/", store::fragment_path(&env, "y"), &env);
        let removed = routes.remove_identity("x");
        assert_eq!(removed, vec!["/a/".to_string(), "/b/".to_string()]);
        assert_eq!(routes.entries.len(), 1);
        assert_eq!(routes.entries[0].identity(), Some("y"));
    }

    #[test]
    fn longest_match_picks_deepest() {
        let env = test_env();
        let mut routes = Routes::default();
        routes.set_route("/dev/", store::fragment_path(&env, "personal"), &env);
        routes.set_route("/dev/work/", store::fragment_path(&env, "work"), &env);

        let m = routes.longest_match("/dev/work/repo/sub/").unwrap();
        assert_eq!(m.identity(), Some("work"));
        let m = routes.longest_match("/dev/other/").unwrap();
        assert_eq!(m.identity(), Some("personal"));
        assert!(routes.longest_match("/elsewhere/").is_none());
        // Exact match of the routed dir itself.
        let m = routes.longest_match("/dev/work/").unwrap();
        assert_eq!(m.identity(), Some("work"));
    }

    #[test]
    fn foreign_blocks_are_preserved_verbatim() {
        let env = test_env();
        let text = "\
# header comment

[includeIf \"gitdir:/home/test/dev/\"]
\tpath = \"/home/test/.config/git-id/identities/personal.gitconfig\"

[includeIf \"onbranch:main\"]
\tpath = /elsewhere/foo.inc

[user]
\tname = sneaky
";
        let routes = parse(text, &env);
        assert_eq!(routes.entries.len(), 1);
        assert_eq!(routes.entries[0].identity(), Some("personal"));
        assert_eq!(routes.preserved.len(), 2);
        assert!(routes.preserved[0].contains("onbranch:main"));
        assert!(routes.preserved[1].contains("sneaky"));

        // Preserved blocks survive a render/parse cycle.
        let reparsed = parse(&render(&routes), &env);
        assert_eq!(reparsed.preserved, routes.preserved);
        assert_eq!(reparsed.entries, routes.entries);
    }

    #[test]
    fn foreign_gitdir_entries_stay_entries_but_unmanaged() {
        let env = test_env();
        let text = "[includeIf \"gitdir:/work/\"]\n\tpath = ~/company.inc\n";
        let routes = parse(text, &env);
        assert_eq!(routes.entries.len(), 1);
        assert!(!routes.entries[0].managed);
        assert_eq!(routes.entries[0].identity(), None);
        // `~` in hand-written targets is expanded against home.
        assert_eq!(
            routes.entries[0].target,
            PathBuf::from("/home/test/company.inc")
        );
    }

    #[test]
    fn gitdir_i_condition_is_foreign() {
        let env = test_env();
        let text = "[includeIf \"gitdir/i:/case/\"]\n\tpath = /x.inc\n";
        let routes = parse(text, &env);
        assert!(routes.entries.is_empty());
        assert_eq!(routes.preserved.len(), 1);
    }

    #[test]
    fn subsection_escaping_roundtrips() {
        let gitdir = "/odd \"quoted\"/back\\slash/";
        let escaped = escape_subsection(gitdir);
        assert_eq!(unescape_subsection(&escaped), gitdir);

        let env = test_env();
        let mut routes = Routes::default();
        routes.set_route(gitdir, store::fragment_path(&env, "odd"), &env);
        let reparsed = parse(&render(&routes), &env);
        assert_eq!(reparsed.entries[0].gitdir, gitdir);
    }

    #[test]
    fn value_quoting_roundtrips() {
        assert_eq!(
            unquote_value(&quote_value("/with space/x.gitconfig")),
            "/with space/x.gitconfig"
        );
        assert_eq!(
            unquote_value(&quote_value("/with\"quote/")),
            "/with\"quote/"
        );
        assert_eq!(
            unquote_value("/bare/path  # trailing comment"),
            "/bare/path"
        );
    }

    #[test]
    fn dangling_gitdir_header_is_preserved() {
        let env = test_env();
        let text = "[includeIf \"gitdir:/dangling/\"]\n";
        let routes = parse(text, &env);
        assert!(routes.entries.is_empty());
        assert_eq!(routes.preserved.len(), 1);
    }
}
